// This file is generated by `studio sync`
declare module "astro:db" {
  export const db: import("@astrojs/db/runtime").SqliteDB;
  export const dbUrl: string;

  export const ProgramsTable: import("@astrojs/db/runtime").Table<
    "ProgramsTable",
    {
      id: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "id";
          collection: "ProgramsTable";
          primaryKey: true;
        };
      };
      goal: {
        type: "text";
        schema: {
          unique: false;
          deprecated: false;
          name: "goal";
          collection: "ProgramsTable";
          primaryKey: false;
          optional: false;
        };
      };
      program: {
        type: "json";
        schema: {
          optional: false;
          unique: false;
          deprecated: false;
          name: "program";
          collection: "ProgramsTable";
        };
      };
    }
  >;
}
